AWSTemplateFormatVersion: '2010-09-09'
Description: Create Deadline Cloud worker image for customer managed fleet (CMF) using
  imagebuilder.
Parameters:
  NamePrefix:
    Type: String
    Description: A prefix for naming resources
    AllowedPattern: ^[a-zA-Z0-9][a-zA-Z0-9-_]*[a-zA-Z0-9]$
    MinLength: 1
    MaxLength: 64
    ConstraintDescription: Name prefix must start and end with alphanumeric characters
      and contain only letters, numbers, hyphens (-), and underscores (_)
  FarmId:
    Type: String
    Description: ID of the render farm.
  FleetName:
    Type: String
    Description: The name of the render farm stack.
    ConstraintDescription: Please enter the render farm stack name
  InstanceTypes:
    Type: CommaDelimitedList
    Description: "A comma separated list of instance types to be used by Image Builder\
      \ to create the image. For example: 'g4dn.xlarge,m5a.large'"
    Default: c6a.xlarge
  Vpc:
    Type: AWS::EC2::VPC::Id
    Description: VPC to launch the Image Builder instance in.
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets to run Deadline Worker instance.
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security group with the required inbound and outbound rules to allow
      Image Builder to access resources in the VPC
  OperatingSystem:
    Type: String
    Description: The operating system of the render farm.
    Default: LINUX
    AllowedValues:
    - LINUX
    - WINDOWS
  MaxWorkerCount:
    Type: Number
    Description: The maximum number of workers in the fleet.
    Default: 10
    MinValue: 1
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Basic Settings
      Parameters:
      - NamePrefix
    - Label:
        default: Render Farm Settings
      Parameters:
      - FarmId
      - FleetName
    - Label:
        default: Render Worker Settings
      Parameters:
      - Vpc
      - SubnetIds
      - SecurityGroupIds
      - InstanceTypes
      - OperatingSystem
      - MaxWorkerCount
    ParameterLabels:
      NamePrefix:
        default: Name prefix
      FarmId:
        default: Render farm ID
      FleetName:
        default: Render Worker Fleet Name
      Vpc:
        default: VPC (Virtual Private Cloud)
      SubnetIds:
        default: Subnet IDs
      SecurityGroupIds:
        default: Security group IDs
      InstanceTypes:
        default: Instance types
      OperatingSystem:
        default: Operating system
      MaxWorkerCount:
        default: Maximum worker count
Conditions:
  IsWindows:
    Fn::Equals:
    - Ref: OperatingSystem
    - WINDOWS
  IsLinux:
    Fn::Equals:
    - Ref: OperatingSystem
    - LINUX
Resources:
  FleetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/dodgy-bros-cf-templates/DeadlineCloudCmfStack.yml
      Parameters:
        NamePrefix:
          Ref: NamePrefix
        FarmId:
          Ref: FarmId
        FleetName:
          Ref: FleetName
        OpperatingSystem:
          Ref: OperatingSystem
        MaxWorkerCount:
          Ref: MaxWorkerCount
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${NamePrefix}-FleetStack
  RenderWorkerImageWindowsStack:
    Type: AWS::CloudFormation::Stack
    Condition: IsWindows
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/dodgy-bros-cf-templates/CmfWindowsImageBuilder.yml
      Parameters:
        NamePrefix:
          Ref: NamePrefix
        FarmId:
          Ref: FarmId
        FleetId:
          Fn::GetAtt:
          - FleetStack
          - Outputs.FleetId
        InstanceTypes:
          Ref: InstanceTypes
        Vpc:
          Ref: Vpc
        SubnetIds:
          Ref: SubnetIds
        SecurityGroupId:
          Ref: SecurityGroupIds
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${NamePrefix}-RenderWorkerImageBuilder
  RenderWorkerImageLinuxStack:
    Type: AWS::CloudFormation::Stack
    Condition: IsLinux
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/dodgy-bros-cf-templates/CmfLinuxImageBuilder.yml
      Parameters:
        NamePrefix:
          Ref: NamePrefix
        FarmId:
          Ref: FarmId
        FleetId:
          Fn::GetAtt:
          - FleetStack
          - Outputs.FleetId
        InstanceTypes:
          Ref: InstanceTypes
        Vpc:
          Ref: Vpc
        SubnetIds:
          Ref: SubnetIds
        SecurityGroupId:
          Ref: SecurityGroupIds
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${NamePrefix}-RenderWorkerImageBuilder
  QueueStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/dodgy-bros-cf-templates/DeadlineCloudQueue.yml
      Parameters:
        NamePrefix:
          Ref: NamePrefix
        FarmId:
          Ref: FarmId
        FleetId:
          Fn::GetAtt:
          - FleetStack
          - Outputs.FleetId
        PasswordSecretArn:
          Fn::If:
          - IsWindows
          - Fn::GetAtt:
            - WindowsRenderWorkerImageStack
            - Outputs.RenderUserPasswordSecret
          - Fn::GetAtt:
            - LinuxRenderWorkerImageStack
            - Outputs.RenderUserPasswordSecret
        BucketName: null
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${NamePrefix}-QueueStack
  AutoScaleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/dodgy-bros-cf-templates/DeadlineCMFAutoscale.yml
      Parameters:
        NamePrefix:
          Ref: NamePrefix
        FleetId:
          Fn::GetAtt:
          - FleetStack
          - Outputs.FleetId
        MaxWorkerCount:
          Ref: MaxWorkerCount
        AMIId:
          Fn::If:
          - IsWindows
          - Fn::GetAtt:
            - WindowsRenderWorkerImageStack
            - Outputs.ImageId
          - Fn::GetAtt:
            - LinuxRenderWorkerImageStack
            - Outputs.ImageId
        Vpc:
          Ref: Vpc
        SubnetIds:
          Ref: SubnetIds
        SecurityGroupIds:
          Ref: SecurityGroupIds
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${NamePrefix}-AutoScaleStack
  EventInfraStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-southeast-2.amazonaws.com/dodgy-bros-cf-templates/DeadlineEventInfraStack.yml
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${NamePrefix}-EventInfraStack
